language: node_js
sudo: false
node_js:
  - '7'
before_script:
  - yarn build
script:
  - yarn travis

deploy:
  - provider: script
    script: yarn build
    skip_cleanup: true
  - provider: surge
    project: ./dist
    domain: brandonslade.me
    skip_cleanup: true
  - provider: surge
    project: ./dist
    domain: brandonslade.surge.sh
    skip_cleanup: true
